export { default as NavBar } from "./NavBar";
export { default as MyAccountNavBar } from "./MyAccountNavBar";
export { default as GeneralInput } from "./GeneralInput";
export { default as AccountSummary } from "./AccountSummury";
export { default as TransactionHistory } from "./TransactionHistory";
export { default as PersonalDetails } from "./PersonalDetails";
export { default as RecentActivities } from "./RecentActivities";
export { default as TransferFunds } from "./TransferFunds";
export { default as MakeAPayment } from "./MakeAPayment";
export {default as Footer } from "./Footer";